language: node_js
node_js:
  - 10.13.0
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm ci
before_script:
  - npm install
script:
  - npm ts
  - npm run lint:js
  - npm test
  - npm run e2e
