backend:
  name: git-gateway
  branch: feature/cms
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

site_url: https://example.com/
display_url: https://example.com/

collections:
  - name: "categories"
    label: "Task Categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "categories"}
      - {label: "Name", name: "category_name", widget: "string"}
      - {label: "Short Description", name: "category_introduction", widget: "markdown"}
      - {label: "Order", name: "order", widget: "number"}
  - name: "tags"
    label: "Task Tags"
    folder: "content/tags"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "tag"}
      - {label: "Name", name: "tag_name", widget: "string"}
  - name: "tasks"
    label: "Checklist Tasks"
    folder: "content/tasks"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "tasks"}
      - {label: "Task Name", name: "task_name", widget: "string"}
      - {label: "Task Category", name: "task_category", widget: "relation", multiple: true, collection: "categories", searchFields: "Name", valueField: "category_name", displayFields: "category_name"}
      - {label: "Task Tags", name: "task_tags", widget: "relation", multiple: true, collection: "tags", searchFields: "Name", valueField: "tag_name", displayFields: "tag_name"}
      - {label: "Task Priority", name: "task_priority", widget: "select", options: ["low", "medium", "high"]}
      - {label: "Task Description", name: "task_detailed_description", widget: "markdown"}
      - {label: "Task Solution", name: "task_solution", widget: "markdown"}
