backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: CMS - Create {{collection}} “{{slug}}”
    update: CMS - Update {{collection}} “{{slug}}”
    delete: CMS - Delete {{collection}} “{{slug}}”
    uploadMedia: CMS - Upload “{{path}}”
    deleteMedia: CMS - Delete “{{path}}”

site_url: https://el-checklist.netlify.com
display_url: https://el-checklist.netlify.com
logo_url: /admin/logo_elp.svg
publish_mode: editorial_workflow
media_folder: public/cms/uploads
public_folder: /cms/uploads

collections:
  - name: "tags"
    label: "Task Tags"
    folder: "content/tags"
    format: "json"
    extension: "json"
    identifier_field: name
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "tag" }
      - { label: "Name", name: "name", widget: "string" }
  - name: "tasks"
    label: "Checklist Tasks"
    folder: "content/tasks"
    format: "json"
    extension: "json"
    identifier_field: name
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "tasks"}
      - { label: "Task Name", name: "name", widget: "string"}
      - { label: "Task Tags", required: false, name: "tags", widget: "relation", multiple: true, collection: "tags", searchFields: "Name", valueField: "name", displayFields: "name" }
      - { label: "Task Priority", name: "severity", widget: "select", options: [1, 2, 3] }
      - { label: "Task Description", name: "description", widget: "markdown" }
      - { label: "Task Solution", required: false, name: "solution", widget: "markdown" }
  - name: "checklists"
    label: "Checklists"
    folder: "content/checklists"
    format: "json"
    extension: "json"
    identifier_field: name
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "checklist"}
      - { label: "Checklist Name", name: "name", widget: "string"}
      - label: "Sections"
        name: "sections"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string"}
          - { label: "Tasks", name: "tasks",  widget: "relation", multiple: true, collection: "tasks", searchFields: ["name", "tags"], valueField: "name", displayFields: ["name", "tags"] }
